ALTER TABLE decks
  ADD COLUMN isCommander     TINYINT(1)   NOT NULL DEFAULT 0,
  ADD COLUMN commanderColors VARCHAR(50)  NULL DEFAULT NULL,
  ADD COLUMN commanderName   VARCHAR(255) NULL DEFAULT NULL;
